[project]
name = "formatadordeexel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "tk>=0.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
